### ISSUE TITLE
Multiple style images: file not found

### ISSUE THREAD

**Issue by wraybowling** [jcjohnson/neural-style#148]
When trying to use two images for a style...

`-style_image ~/Desktop/cyberpunk.jpg,~/Desktop/steampunk.jpg`

I always get an error for the second path (and beyond)

```
/home/parallels/torch/install/bin/luajit: /home/parallels/torch/install/share/lua/5.1/image/init.lua:346: ~/Desktop/steampunk.jpg: No such file or directory
stack traceback:
	[C]: in function 'error'
	/home/parallels/torch/install/share/lua/5.1/image/init.lua:346: in function 'load'
	neural_style.lua:90: in function 'main'
	neural_style.lua:500: in main chunk
	[C]: in function 'dofile'
	...lels/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
```

**Comment by 3DTOPO** [comment]
Try putting the image list in quotes:

     -style_image "~/Desktop/cyberpunk.jpg,~/Desktop/steampunk.jpg"

**Comment by wraybowling** [comment]
That didn't work. Now it's complaining about "No such file" for the first item in the list.

**Comment by htoyryla** [comment]
Wray Bowling <notifications@github.com> kirjoitti 3.3.2016 kello 15.26:

> That didn't work. Now it's complaining about "No such file" for the first item in the list.
> 
Try using the full path instead of ~/

I made some tests using th interpreter and on my setup loading the image always fails using ~/ instead of the full path.

th> img = image.load("~/Pictures/sibir_0003.jpg",3)
/home/hannu/torch/install/share/lua/5.1/image/init.lua:346: ~/Pictures/sibir_0003.jpg: No such file or directory
stack traceback:
	[C]: in function 'error'
	/home/hannu/torch/install/share/lua/5.1/image/init.lua:346: in function 'load'
	[string "img = image.load("~/Pictures/sibir_0003.jpg",3)"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/hannu/torch/install/share/lua/5.1/trepl/init.lua:669: in function 'repl'
	...annu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670	
                                                                      [0.0003s]
th> img = image.load("/home/hannu/Pictures/sibir_0003.jpg",3)   [0.0426s]

br,
Hannu

**Comment by wraybowling** [comment]
Absolute paths work! Thank you @htoyryla. Now let's see if @jcjohnson wants to update the documentation.

**Comment by jcjohnson** [comment]
Documentation updated. It looks like the problem is the home directory character `~`; both full absolute paths and relative paths should work.
