### ISSUE TITLE
running out of memory in opencl

### ISSUE THREAD

**Issue by rayset** [jcjohnson/neural-style#152]
I have a radeon r9 280x, everything works good with default settings.

For what I'm understanding the system runs only on my gpu's memory and doesn't use my RAM.

```
kernel source:
1: // from SpatialConvolutionMM.cu:
2: 
3: // CL: grid stride looping
4: #define CL_KERNEL_LOOP(i, n)                        \
5:   for (int i = get_group_id(0) * get_local_size(0) + get_local_id(0); \
6:       i < (n);                                       \
7:       i += get_local_size(0) * get_num_groups(0))
8: 
9: // Kernel for fast unfold+copy
10: // (borrowed from Caffe: https://github.com/BVLC/caffe/blob/master/src/caffe/layers/conv_layer.cu)
11: kernel void im2col_kernel(const int n, const global float* im_data, int im_offset,
12:     const int height, const int width, const int ksize_h, const int ksize_w, const int pad_h,
13:     const int pad_w, const int stride_h, const int stride_w, const int height_col, const int width_col,
14:     global float* col_data, int col_offset) {
15:   global const float *data_im = im_data + im_offset;
16:   global float *data_col = col_data + col_offset;
17: 
18:   CL_KERNEL_LOOP(index, n) {
19:     int w_out = index % width_col;
20:     index /= width_col;
21:     int h_out = index % height_col;
22:     int channel_in = index / height_col;
23:     int channel_out = channel_in * ksize_h * ksize_w;
24:     int h_in = h_out * stride_h - pad_h;
25:     int w_in = w_out * stride_w - pad_w;
26:     data_col += (channel_out * height_col + h_out) * width_col + w_out;
27:     data_im += (channel_in * height + h_in) * width + w_in;
28:     for (int i = 0; i < ksize_h; ++i) {
29:       for (int j = 0; j < ksize_w; ++j) {
30:         int h = h_in + i;
31:         int w = w_in + j;
32:         *data_col = (h >= 0 && w >= 0 && h < height && w < width) ?
33:           data_im[i * width + j] : 0;
34:         data_col += height_col * width_col;
35:       }
36:     }
37:   }
38: }
39: 
40: kernel void col2im_kernel(const int n, global const float* col_data, int col_offset,
41:     const int height, const int width, const int channels, const int patch_h, const int patch_w,
42:     const int pad_h, const int pad_w, const int stride_h, const int stride_w,
43:     const int height_col, const int width_col,
44:     global float* im_data, int im_offset) {
45:   global float *data_im = im_data + im_offset;
46:   global const float *data_col = col_data + col_offset;
47: 
48:   CL_KERNEL_LOOP(index, n) {
49:     float val = 0;
50:     int w = index % width + pad_w;
51:     int h = (index / width) % height + pad_h;
52:     int c = index / (width * height);
53:     // compute the start and end of the output
54:     int w_col_start = (w < patch_w) ? 0 : (w - patch_w) / stride_w + 1;
55:     int w_col_end = min(w / stride_w + 1, width_col);
56:     int h_col_start = (h < patch_h) ? 0 : (h - patch_h) / stride_h + 1;
57:     int h_col_end = min(h / stride_h + 1, height_col);
58:     /*
59:        for (int h_col = h_col_start; h_col < h_col_end; ++h_col) {
60:        for (int w_col = w_col_start; w_col < w_col_end; ++w_col) {
61:     // the col location: [c * width * height + h_out, w_out]
62:     int c_col = c * patch_h * patch_w + (h - h_col * stride_h) * ksize + (w - w_col * stride_w);
63:     val += data_col[(c_col * height_col + h_col) * width_col + w_col];
64:     }
65:     }
66:      */
67:     // equivalent implementation
68:     int offset = (c * patch_h * patch_w + h * patch_w + w) * height_col * width_col;
69:     int coeff_h_col = (1 - stride_h * patch_w * height_col) * width_col;
70:     int coeff_w_col = (1 - stride_w * height_col * width_col);
71:     for (int h_col = h_col_start; h_col < h_col_end; ++h_col) {
72:       for (int w_col = w_col_start; w_col < w_col_end; ++w_col) {
73:         val += data_col[offset + h_col * coeff_h_col + w_col * coeff_w_col];
74:       }
75:     }
76:     data_im[index] = val;
77:   }
78: }
79: 
80: 

Memory object allocation failure, code -4
/home/alex/torch/install/bin/luajit: /home/alex/torch/install/share/lua/5.1/nn/THNN.lua:1091: 
kernel source:
1: // from SpatialConvolutionMM.cu:
2: 
3: // CL: grid stride looping
4: #define CL_KERNEL_LOOP(i, n)                        \
5:   for (int i = get_group_id(0) * get_local_size(0) + get_local_id(0); \
6:       i < (n);                                       \
7:       i += get_local_size(0) * get_num_groups(0))
8: 
9: // Kernel for fast unfold+copy
10: // (borrowed from Caffe: https://github.com/BVLC/caffe/blob/master/src/caffe/layers/conv_layer.cu)
11: kernel void im2col_kernel(const int n, const global float* im_data, int im_offset,
12:     const int height, const int width, const int ksize_h, const int ksize_w, const int pad_h,
13:     const int pad_w, const int stride_h, const int stride_w, const int height_col, const int width_col,
14:     global float* col_data, int col_offset) {
15:   global const float *data_im = im_data + im_offset;
16:   global float *data_col = col_data + col_offset;
17: 
18:   CL_KERNEL_LOOP(index, n) {
19:     int w_out = index ?
stack traceback:
	[C]: in function 'v'
	/home/alex/torch/install/share/lua/5.1/nn/THNN.lua:1091: in function 'SpatialConvolutionMM_updateOutput'
	...ex/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:104: in function 'updateOutput'
	/home/alex/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	neural_style.lua:204: in function 'main'
	neural_style.lua:500: in main chunk
	[C]: in function 'dofile'
	...alex/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d70

```
I don't know what error code -4 is, but I read a couple of other open issues and found that I may try with adam since I could be running out of gpu's memory. still,even using adam, for a 1000px image I get the same error. I can do 512px images with no problems.

Is there a way to use my RAM to store the network (or whatever is this uge) but still use the gpu's over the cpu? of course it would be slower than pure gpu, but at least I could have it running.

**Comment by jcjohnson** [comment]
I'm pretty sure that the source you posted is for the CUDA backend; the OpenCL backend is provided by cltorch:

https://github.com/hughperkins/cltorch

You are certainly running out of memory; looks like the radeon r9 280x has 3GB of VRAM? That's not enough for large images. OpenCL probably also uses more memory that CUDA + cuDNN, since I believe the OpenCL backend uses an im2col implementation for convolutions rather than a direct approach like cuDNN.

What uses all the memory is not the network weights, but the convolutional feature maps of the input image; there is no easy way to store these on host memory and shuffle the to the GPU as needed. It would theoretically be possible, but not easy to implement in torch; it would also be disastrous for performance since you would be shuffling gigabytes of data back and forth between host and GPU in the hot loop.

**Comment by rayset** [comment]
that source is the one provided me in the terminal, I was wondering the same. I did put the right backend parameter too.

I think I will go cloud someway then, thanks for the reply.

**Comment by daemontus** [comment]
Hi, not sure where to write this, but hopefully someone will find it here :) (and maybe not a bad idea to put this into the readme)
Make sure you also resize the style and content images to roughly the size of your desired result. Otherwise the image size flag doesn't help much. To give you an idea:
I am also running on Radeon 280x. I can compute with source images that are roughly 250x200 pixels, but everything higher produces a segmentation fault (seems memory related). If I have a source image that is bigger (500px for example), but I set the output size to something very small, say 50, it's still going to fail, because the source is so big.

**Comment by htoyryla** [comment]
Samuel Pastva <notifications@github.com> kirjoitti 20.3.2016 kello 14.23:

> Hi, not sure where to write this, but hopefully someone will find it here :) (and maybe not a bad idea to put this into the readme)
> Make sure you also resize the style and content images to roughly the size of your desired result. Otherwise the image size flag doesn't help much. To give you an idea:
> I am also running on Radeon 280x. I can compute with source images that are roughly 250x200 pixels, but everything higher produces a segmentation fault (seems memory related). If I have a source image that is bigger (500px for example), but I set the output size to something very small, say 50, it's still going to fail, because the source is so big.
> 


This is probably because neural-style DOES resize both images to image_size, and if the original images are large this may require too much memory. 

In general there is no need to rescale images beforehand, but, as you say, it may help if one is severely constrained by memory.

Hannu
