### ISSUE TITLE
"Size Mismatch" on some images

### ISSUE THREAD

**Issue by salamanders** [jcjohnson/neural-style#19]
Sometimes it works great.  Other combos of images, it gets unhappy.  Not sure what triggers it, haven't found a pattern yet.

```
th neural_style.lua -style_image monet_child_flowers.png -content_image fire_truck.png -gpu -1
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
WARNING: Skipping content loss	
/Users/ME/torch/install/bin/luajit: ...rs/ME/torch/install/share/lua/5.1/nn/Sequential.lua:44: size mismatch, m1: [64 x 27], m2: [36 x 200192] at /tmp/luarocks_torch-scm-1-4776/torch7/lib/TH/generic/THTensorMath.c:657
stack traceback:
	[C]: in function 'updateOutput'
	...rs/ME/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	neural_style.lua:155: in function 'main'
	neural_style.lua:375: in main chunk
	[C]: in function 'dofile'
	...hill/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x0108c3a2f0

**Comment by jcjohnson** [comment]
Wow, that shouldn't happen! Can you provide the images?

**Comment by anjishnu** [comment]
I am not sure what causes this issue - I got it when I was using a png content image, I used imagemagick to convert it into a jpg and the error disappeared.

**Comment by jcjohnson** [comment]
If you run into another pair of images that gives this error, please send them to me so I can debug.

**Comment by alexjc** [comment]
Is the `WARNING: Skipping content loss` part expected/common? I get it almost all the time, it's due to a mismatch in the buffers, and happens once or twice then goes away...

**Comment by salamanders** [comment]
I get "WARNING: Skipping content loss" plenty.  May be unrelated?

**Comment by jcjohnson** [comment]
The `WARNING: Skipping content loss` is expected a couple of times at the beginning. If it shows up during every iteration however then something is seriously wrong.

It turns out that there was a size error when one of the images was RGBA; I suspect that this is the problem that @anjishnu was running into, since converting from PNG to JPG probably removed the alpha channel from the image. The bug should be fixed in https://github.com/jcjohnson/neural-style/commit/15ad5e515c6845a827f1c978d6ba6a3ba1925149 so I'm going to close this issue.

**Comment by dpflug** [comment]
I'm getting this on all images:

$ th neural_style.lua -gpu -1 -style_layers examples/inputs/starry_night.jpg -content_layers examples/inputs/brad_pitt.jpg
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
/home/dpflug/projects/deepstyle/torch/install/bin/luajit: ...ects/deepstyle/torch/install/share/lua/5.1/nn/Linear.lua:39: size mismatch, [4096 x 25088], [98304] at /home/dpflug/projects/deepstyle/torch/pkg/torch/lib/TH/generic/THTensorMath.c:608
stack traceback:
	[C]: in function 'addmv'
	...ects/deepstyle/torch/install/share/lua/5.1/nn/Linear.lua:39: in function 'updateOutput'
	.../deepstyle/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	neural_style.lua:220: in function 'main'
	neural_style.lua:454: in main chunk
	[C]: in function 'dofile'
	...tyle/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x55aa749a19c0

**Comment by jcjohnson** [comment]
You should be using the `-style_image` and `-content_image` flags instead of `-style_layers` and `-content_layers`. The latter are for setting which layers of the CNN to use for style and content reconstruction; the defaults should work well for most cases.

**Comment by dpflug** [comment]
Well, now I feel foolish for resurrecting this. My apologies!

**Comment by kidapu** [comment]
I'm getting this error.. Do you know what happened for me ?

```
$ th neural_style.lua -style_image style.jpg -content_image content.jpg -output_image result.jpg -gpu -1 -print_iter 1 -save_iter 5
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
/usr/local/bin/luajit: /usr/local/share/lua/5.1/nn/Linear.lua:39: size mismatch, [4096 x 25088], [73728] at /tmp/luarocks_torch-scm-1-9022/torch7/lib/TH/generic/THTensorMath.c:608
stack traceback:
	[C]: in function 'addmv'
	/usr/local/share/lua/5.1/nn/Linear.lua:39: in function 'updateOutput'
	/usr/local/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	neural_style.lua:265: in function 'main'
	neural_style.lua:500: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406260
```
