### ISSUE TITLE
Code is running much slower in CPU mode than documentation suggests

### ISSUE THREAD

**Issue by anjishnu** [jcjohnson/neural-style#21]
I've been running it on one a single image for over 12 hours now, and it's only gone through 500 iterations.

CPU:
model name      : Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

Speed difference shouldn't be so high. I am using default parameters.

**Comment by dodekeract** [comment]
It really depends on the image dimensions. How big are your input and output images?

**Comment by jcjohnson** [comment]
In CPU mode, torch should use multiple threads by calling into multithreaded BLAS. The i5-3470 CPU is a quad-core processor, so make sure that it is actually using 4 threads. I suspect that there's something wrong with your BLAS installation; maybe it is only using one thread for some reason?

I also just reran default parameters in CPU mode on my i7-4790k (quad core with hyperthreading = 8 threads) and I get through 50 iterations in about 2.5 minutes; I'd expect the i5-3470 to be slower than the 4790k, but not 30x slower.

**Comment by anjishnu** [comment]
I think the image sizes shouldn't be a huge issue since they are on the same order of magnitude as the images in the sample.

Content Image:
custom.jpg JPEG 900x974 85KB

Style Image:
the_scream.jpg JPEG 1200x1528 1200x1528+0+0 8-bit DirectClass 217KB 0.000u 0:00.000

I'll dig into the blas issue.

**Comment by SirSpunky** [comment]
I've been running it on a pretty old CPU, an Intel Core i5 2500K 3,3GHz, and with an output image size of 256 it runs 500 iterations in about 10 minutes.

Could it be that you're trying to generate too large images (such as 512), which causes it to use virtual memory instead of RAM, slowing down the generation? Try to run it with "-image_size 256" and see if it gets better, 256 was the largest output resolution I could generate with about 4 GB RAM running on the CPU. If that doesn't help, it's probably a software/installation issue.

**Comment by anjishnu** [comment]
^I think this was it - after reducing the size of the output image somewhat, the code started running much faster O(~hour) rather than O(days)
