### ISSUE TITLE
strategies for improving frame-to-frame consistency?

### ISSUE THREAD

**Issue by genekogan** [jcjohnson/neural-style#22]
i'm trying to create animations but find large variations in high level features from frame to frame. initializing with the content image instead of noise reduces the inconsistency but also reduces the style transfer. are there any ways around this? maybe producing an initial image from initializing with the content image, then feeding that back and initializing with noise to produce over that?  or some blending approach perhaps? or is there a parameter combination that may achieve this instead?

**Comment by alexjc** [comment]
OK, some semi-random and semi-informed thoughts:

* Pick images that match the composition of the frame well. I think oscillation is due to the algorithm struggling to find a clear optimum, so it ends up having to put extreme features (e.g. colors) somewhere inappropriate.
* If you want to keep an image whose style and composition doesn't match well, try disabling disable top 1-2 layers of style loss (or more).  This should put less emphasis on the composition of the whole scene and cause more local variations.
* Wondering if doing a moving average of three frames as the content image would help with temporal consistency at the low-level.. I guess you'd need to detect cuts and only average 2 frames in those cases.

I hope this helps! I haven't done video yet but seen lots of weird edge cases with [@DeepForger](http://twitter.com/DeepForger) so starting to learn from the patterns :-)

**Comment by jcjohnson** [comment]
Another idea for temporal consistency is to initialize the optimization for frame t+1 with the result of optimization from frame t. Initializing with the something other than noise or the content image isn't implemented right now, but it would be easy to add.

**Comment by bododge** [comment]
It would be great if you could initialize on a the previous frame. I know I have read others who have implemented just that, but I can't figure it out.
