### ISSUE TITLE
Tuning style parameters

### ISSUE THREAD

**Issue by briedis** [jcjohnson/neural-style#308]
Sorry, this is not really an issue, but I didn't know where to write.

I found out about this project from ostagram.ru.

When I generated an image there, it had weight 300, scale 1 and I got this result:
![image](https://cloud.githubusercontent.com/assets/500491/17705020/99852590-63df-11e6-80e7-aeafa83a62f0.png)

Using the same parameters (1, 300) with this model, I got only something like this:
![image](https://cloud.githubusercontent.com/assets/500491/17705095/d516b826-63df-11e6-9fc5-c733202603f5.png)

This is the closest I got, using scale 1.25, weight 500:
![image](https://cloud.githubusercontent.com/assets/500491/17705057/b16c10e2-63df-11e6-9392-707c09be1d57.png)

Any idea what ostagram.ru could be using more, to achieve this better, cleaner look (Look how they managed to preserve sunglasses form without artefacts)? 

Style image: https://ost6imgs.s3.eu-central-1.amazonaws.com/uploads/style/image/19363/img_ac86663121.jpg
Source image: https://ost6imgs.s3.eu-central-1.amazonaws.com/uploads/content/image/649943/img_283f124f54.jpg

**Comment by sheerun** [comment]
Here are my results: ![](https://i.imgsafe.org/5f71733d87.png)

If you're interested in the parameters I figured out, please visit:
https://buy.sheerun.net/products/deepart-io-neural-style-parameters

**Comment by transfluxus** [comment]
maybe they are using
https://github.com/DmitryUlyanov/texture_nets

**Comment by sheerun** [comment]
Only on http://turbo.deepart.io/

**Comment by kineticsystem** [comment]
Use the following parameters. They are for CPU because I do not have a GPU powerful enough to generate a 768 wide picture. It may take a bit, but I tried with your picture and the result is quite good.

th neural_style.lua \
-style_image test_style.jpg \
-content_image test_input.jpg  \
-output_image out-cpu/out.png \
-gpu -1 \
-backend cudnn \
-save_iter 10 \
-cudnn_autotune \
-style_scale 1 \
-image_size 768 \
-content_weight 5 \
-style_weight 100 \
-init image

**Comment by briedis** [comment]
@kineticsystem Awesome! I'll try as soon as possible :) Thanks!

**Comment by kineticsystem** [comment]
This is what I got after 640 iterations.
![out_640](https://cloud.githubusercontent.com/assets/5970998/17984650/1519c9a0-6b0a-11e6-92cd-623e7d790dbf.png)

**Comment by briedis** [comment]
Wow, the result is amazing! I think that you can start charging $50 too, or even $55 :joy: 

You said that this is for CPU. CPU can generate a bigger picture with less memory, but it takes longer? Because as I understand, to generate a 1000px image you need at least like 10 gigs of memory with a GPU ..

**Comment by kineticsystem** [comment]
In fairness they are all default parameters except "-init image" which makes the difference.
With my GPU I can generate up to 600px wide, but it depends on the style scale too, the smaller the scale the smaller the memory. You need a lot of memory when using CPU but I cannot say how much because I haven't monitored.
As far as I've experienced with this software the bigger the image the less the quality of the result so if you want a bigger image I suggest you to enlarge it with some other software. I have no idea how to increase the size of the image while keeping the same appearance.

**Comment by briedis** [comment]
@kineticsystem huge thanks for your help!

Yeah, I heard that the bigger the size, the worse result. I'll try using waifu upscaling. 1.6x seems to do very fine!

Thanks for everything, you're awesome!

**Comment by briedis** [comment]
@kineticsystem hey, sorry to bump such an old post. I got my self a gtx 1060, but it kinda processes really slow - 1000 iterations take like an hour. How fast did you get the result? I'm not sure if I need to configure my cuda drivers, parameters or something, it my card just won't process it any faster?

**Comment by htoyryla** [comment]
@briedis it sounds like you are not using the GPU at all. Did you remember to use -gpu 0 on the command line? Also, to get full speed, you need cudnn (-backend cudnn on the command line).

Not knowing what you have already installed, this may give errors. If so, report back here.

**Comment by briedis** [comment]
@htoyryla indeed, sorry for my stupidness, indeed I was running it with 1 thinking it meant it turned on :D

**Comment by sheerun** [comment]
Here are parameters I've used:

```
th neural_style.lua \
-style_image $(pwd)/style.jpg \
-content_image $(pwd)/content.jpg \
-output_image $(pwd)/output.jpg \
-gpu 0 \
-init image \
-content_weight 5 \
-style_weight 1000 \
-style_scale 1 \
-image_size 500 \
-num_iterations 1000 \
-cudnn_autotune \
-backend cudnn \
-tv_weight 0.001
```

Please like this comment if they work for you, thank you
