### ISSUE TITLE
non-issue: Is there any way for 'saving the style' for the purpose of accelerate?

### ISSUE THREAD

**Issue by albertyou2** [jcjohnson/neural-style#347]
@jcjohnson Greate work!  

I wonder if there is a method to save the 'style' that the network just learned from a image.
And then  we could just apply the style to any images.
I guess this will speed up the  learning process?

Thank you very much !

**Comment by htoyryla** [comment]
Not in neural-style, because it does not learn a new style at all. It creates a new image by minimizing the loss compared to the content and style images, using the VGG (or another) model to measure these losses. The model does not change in this process.

You should look into github.com/jcjohnson/fast-neural-style . There, one first trains a model into a filter that transforms the input image into the desired style in one go, without iterations. The training takes a few hours on a GPU. The downside, as I see it, is that creating new styles takes a lot of time, as you need to train a model before you see how the result looks like.

**Comment by albertyou2** [comment]
@htoyryla 
thank you very much !  I got it!
