### ISSUE TITLE
Non Nvidia GPU support?

### ISSUE THREAD

**Issue by LukeOeding** [jcjohnson/neural-style#68]
I was wondering if there are any plans to add support for GPU usage on AMD cards:
For instance, my iMac has an AMD Radeon R9 M295X 4096 MB, but I don't think CUDA works for this.  It would be fun to be able to tap into the GPUs on my computer for this application.

**Comment by jcjohnson** [comment]
Some folks in https://github.com/jcjohnson/neural-style/issues/44 managed to get it working with AMD GPUs using OpenCL. Those changes are not merged into master because they depend on some tweaks to cltorch, but you should be able to checkout their branches and get it working.

I only have NVIDIA GPUs, so I haven't been able to test it myself.

**Comment by hughperkins** [comment]
Hi, following Justin's merge today from @napsternxg , OpenCL should be supported now (using [cltorch](https://github.com/hughperkins/cltorch) and [clnn](https://github.com/hughperkins/clnn) ), https://github.com/jcjohnson/neural-style/pull/98#issuecomment-167186888

**Comment by hughperkins** [comment]
So this can be closed I think? ( But please go ahead and raise any issues or problems that you find at https://github.com/hughperkins/clnn/issues/new )
