### ISSUE TITLE
Grayscale Images

### ISSUE THREAD

**Issue by neilpanchal** [jcjohnson/neural-style#82]
Amazing work!

I was wondering if there are specific optimizations in terms of the initial random tensor that is generated. When I use monochromatic images, both for style & content, I get color noise presumably due to the way the initial randomization is performed.

Any ideas as to restrict the domain to graycale instead of RGB mode - and improve the output as well as perhaps the speed of the computation?

Thanks!

**Comment by jcjohnson** [comment]
I think it would be pretty easy to restrict generated images to be grayscale. You would first make sure your initial random noise was grayscale rather than color, and then at each gradient step you would sum gradients across color channels for each pixel. This would ensure that each gradient update on the generated image maintain the grayscale property, and the final image would be grayscale.

However you wouldn't get any speedups this way. The expensive part is running the generated image through the pretrained VGG network, and this is equally slow for grayscale and color images.
